{
  try {
    return method.invoke(instance,args);
  }
 catch (  IllegalAccessException e) {
    Log.w(TAG,"Unexpected error while invoking " + method,e);
    return null;
  }
catch (  InvocationTargetException e) {
    Log.w(TAG,"Unexpected error while invoking " + method,e.getCause());
    return null;
  }
catch (  RuntimeException re) {
    Log.w(TAG,"Unexpected error while invoking " + method,re);
    return null;
  }
}
